apiVersion: v1
kind: Service
metadata:
  name: spa
  namespace: n8n
  labels:
    app: spa
spec:
  type: ClusterIP
  selector:
    app: spa
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
