# Phase 1B: compose all infrastructure modules.

data "azurerm_client_config" "current" {}

data "azurerm_resource_group" "lab" {
  name = var.resource_group_name
}

# Random suffix for globally-unique resource names (ACR, KV, Postgres).
resource "random_string" "suffix" {
  length  = 4
  upper   = false
  numeric = true
  special = false
}

# ───── Foundational ─────

module "loganalytics" {
  source              = "../../modules/loganalytics"
  workspace_name      = "log-${var.prefix}-sea"
  location            = var.location_primary
  resource_group_name = data.azurerm_resource_group.lab.name
  tags                = var.tags
}

module "acr" {
  source              = "../../modules/acr"
  registry_name       = "acr${var.prefix}${random_string.suffix.result}"
  location            = var.location_primary
  resource_group_name = data.azurerm_resource_group.lab.name
  tags                = var.tags
}

module "keyvault" {
  source              = "../../modules/keyvault"
  vault_name          = "kv-${var.prefix}-sea-${random_string.suffix.result}"
  location            = var.location_primary
  resource_group_name = data.azurerm_resource_group.lab.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  tags                = var.tags

  # KV admin role assignments are bootstrap-managed (see scripts/00-bootstrap-state.sh
  # and ADR 0008). The GHA MI + human admin are granted Key Vault Administrator at
  # RG scope by the bootstrap script, which covers any KV in this RG.
}

# ───── Runtime ─────

module "aks" {
  source              = "../../modules/aks"
  cluster_name        = "aks-${var.prefix}-sea"
  location            = var.location_primary
  resource_group_name = data.azurerm_resource_group.lab.name
  acr_id              = module.acr.id
  log_analytics_id    = module.loganalytics.id
  tags                = var.tags
}

module "openai" {
  source              = "../../modules/openai"
  account_name        = "aoai-${var.prefix}-aue"
  location            = var.location_aoai # australiaeast for GPT-4o (ADR 0004)
  resource_group_name = data.azurerm_resource_group.lab.name
  tags                = var.tags
}

module "postgres" {
  source              = "../../modules/postgres"
  server_name         = "psql-${var.prefix}-sea-${random_string.suffix.result}"
  location            = var.location_primary
  resource_group_name = data.azurerm_resource_group.lab.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  tags                = var.tags
}

# ───── Stash secrets into Key Vault ─────
#
# The Postgres password is generated by the postgres module; we write it to KV so
# Phase 1E can mount it into the n8n pod via env-from-Secret (1E) or CSI (Phase 3).

resource "azurerm_key_vault_secret" "postgres_admin_password" {
  name         = "postgres-admin-password"
  value        = module.postgres.administrator_password
  key_vault_id = module.keyvault.id

  depends_on = [module.keyvault] # RBAC role assignment must complete first
}

resource "azurerm_key_vault_secret" "postgres_admin_login" {
  name         = "postgres-admin-login"
  value        = module.postgres.administrator_login
  key_vault_id = module.keyvault.id

  depends_on = [module.keyvault]
}

resource "azurerm_key_vault_secret" "postgres_fqdn" {
  name         = "postgres-fqdn"
  value        = module.postgres.fqdn
  key_vault_id = module.keyvault.id

  depends_on = [module.keyvault]
}
